/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadIndexRouteImport } from './routes/cad.index'
import { Route as CadDocRouteImport } from './routes/cad.$doc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadIndexRoute = CadIndexRouteImport.update({
  id: '/cad/',
  path: '/cad/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadDocRoute = CadDocRouteImport.update({
  id: '/cad/$doc',
  path: '/cad/$doc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cad/$doc': typeof CadDocRoute
  '/cad/': typeof CadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cad/$doc': typeof CadDocRoute
  '/cad': typeof CadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cad/$doc': typeof CadDocRoute
  '/cad/': typeof CadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cad/$doc' | '/cad/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cad/$doc' | '/cad'
  id: '__root__' | '/' | '/cad/$doc' | '/cad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadDocRoute: typeof CadDocRoute
  CadIndexRoute: typeof CadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad/': {
      id: '/cad/'
      path: '/cad'
      fullPath: '/cad/'
      preLoaderRoute: typeof CadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad/$doc': {
      id: '/cad/$doc'
      path: '/cad/$doc'
      fullPath: '/cad/$doc'
      preLoaderRoute: typeof CadDocRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadDocRoute: CadDocRoute,
  CadIndexRoute: CadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
