/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SysmlRouteImport } from './routes/sysml'
import { Route as CadIndexRouteImport } from './routes/cad.index'
import { Route as CadDocRouteImport } from './routes/cad.$doc'
import { Route as ProjectsBdsRouteImport } from './routes/projects.bds'
import { Route as ProjectsMcrRouteImport } from './routes/projects.mcr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SysmlRoute = SysmlRouteImport.update({
  id: '/sysml',
  path: '/sysml',
  getParentRoute: () => rootRouteImport,
} as any)
const CadIndexRoute = CadIndexRouteImport.update({
  id: '/cad/',
  path: '/cad/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadDocRoute = CadDocRouteImport.update({
  id: '/cad/$doc',
  path: '/cad/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBdsRoute = ProjectsBdsRouteImport.update({
  id: '/projects/bds',
  path: '/projects/bds',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMcrRoute = ProjectsMcrRouteImport.update({
  id: '/projects/mcr',
  path: '/projects/mcr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sysml': typeof SysmlRoute
  '/cad/$doc': typeof CadDocRoute
  '/projects/bds': typeof ProjectsBdsRoute
  '/projects/mcr': typeof ProjectsMcrRoute
  '/cad/': typeof CadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sysml': typeof SysmlRoute
  '/cad/$doc': typeof CadDocRoute
  '/projects/bds': typeof ProjectsBdsRoute
  '/projects/mcr': typeof ProjectsMcrRoute
  '/cad': typeof CadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sysml': typeof SysmlRoute
  '/cad/$doc': typeof CadDocRoute
  '/projects/bds': typeof ProjectsBdsRoute
  '/projects/mcr': typeof ProjectsMcrRoute
  '/cad/': typeof CadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/sysml' | '/cad/$doc' | '/projects/bds' | '/projects/mcr' | '/cad/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sysml' | '/cad/$doc' | '/projects/bds' | '/projects/mcr' | '/cad'
  id:
    | '__root__'
    | '/'
    | '/sysml'
    | '/cad/$doc'
    | '/projects/bds'
    | '/projects/mcr'
    | '/cad/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SysmlRoute: typeof SysmlRoute
  CadDocRoute: typeof CadDocRoute
  ProjectsBdsRoute: typeof ProjectsBdsRoute
  ProjectsMcrRoute: typeof ProjectsMcrRoute
  CadIndexRoute: typeof CadIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sysml': {
      id: '/sysml'
      path: '/sysml'
      fullPath: '/sysml'
      preLoaderRoute: typeof SysmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad/': {
      id: '/cad/'
      path: '/cad'
      fullPath: '/cad/'
      preLoaderRoute: typeof CadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cad/$doc': {
      id: '/cad/$doc'
      path: '/cad/$doc'
      fullPath: '/cad/$doc'
      preLoaderRoute: typeof CadDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/bds': {
      id: '/projects/bds'
      path: '/projects/bds'
      fullPath: '/projects/bds'
      preLoaderRoute: typeof ProjectsBdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/mcr': {
      id: '/projects/mcr'
      path: '/projects/mcr'
      fullPath: '/projects/mcr'
      preLoaderRoute: typeof ProjectsMcrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SysmlRoute: SysmlRoute,
  CadDocRoute: CadDocRoute,
  ProjectsBdsRoute: ProjectsBdsRoute,
  ProjectsMcrRoute: ProjectsMcrRoute,
  CadIndexRoute: CadIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
