"""Is the built UI up to date?

Compares the newest timestamp of the frontend sources with the build in
backend/app/static/. Used by scripts/start.* (rebuilds when needed) and
scripts/doctor.py.

    python scripts/build_status.py      -> prints fresh|stale|missing, exit 0|1|2
"""

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRONTEND = os.path.join(REPO, "frontend")
BUILT_INDEX = os.path.join(REPO, "backend", "app", "static", "index.html")

#: What affects the build. routeTree.gen.ts is generated by the build itself
#: and therefore doesn't count -- otherwise every build would be "stale" right away.
SOURCES = ("src", "index.html", "package.json", "pnpm-lock.yaml", "vite.config.ts",
           "tsconfig.json", "tsconfig.app.json", "components.json")
IGNORED = ("routeTree.gen.ts",)


def newest_source():
    newest, newest_path = 0.0, None
    for entry in SOURCES:
        path = os.path.join(FRONTEND, entry)
        if os.path.isfile(path):
            candidates = [path]
        elif os.path.isdir(path):
            candidates = [
                os.path.join(root, name)
                for root, _dirs, files in os.walk(path)
                for name in files
                if name not in IGNORED
            ]
        else:
            continue
        for candidate in candidates:
            mtime = os.path.getmtime(candidate)
            if mtime > newest:
                newest, newest_path = mtime, candidate
    return newest, newest_path


def status():
    """('fresh'|'stale'|'missing', newest source file)."""
    if not os.path.isfile(BUILT_INDEX):
        return "missing", None
    newest, path = newest_source()
    if newest > os.path.getmtime(BUILT_INDEX):
        return "stale", path
    return "fresh", None


def main():
    state, path = status()
    print(state if path is None else "%s (%s)" % (state, os.path.relpath(path, REPO)))
    return {"fresh": 0, "stale": 1, "missing": 2}[state]


if __name__ == "__main__":
    sys.exit(main())
